### ISSUE TITLE
QT5 build fail

### ISSUE THREAD

**Issue by Mula-Gabriel** [bootlin/buildroot-external-st#16]
i had the same issue as here https://yhbt.net/lore/all/20210703000905.680afb9e@gmx.net/T/
with config st_stm32mp157c_dk2_demo_defconfig while building qt5.15.2

I just added this include in qbytearraymatcher.h
`#include <limits>`

Qt5 build fine now

**Comment by kmaincent** [comment]
Hello, thanks for your feedback.
I don't know which Buildroot version you are using but the patch you mention is merged in version 2021.02.3. Do you still face the issue with this version?
