### ISSUE TITLE
kernel compile failure using Vagrant

### ISSUE THREAD

**Issue by nexus-fd** [bootlin/buildroot-external-st#17]
Kernel compilation failed with error: "scripts/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory".
Failure caused by missing SSH development files, fixed with "sudo apt-get install libssl-dev".
Recommend adding "libssl-dev" to "Vagrantfile", "config.vm.provision", "apt-get -q -y install" section.

**Comment by kmaincent** [comment]
Hello, thanks for your feedback.
Are you using the same kernel Configuration as the one in the BR2_EXTERNAL?
If not, maybe you should enable this Buildroot configuration BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL.

**Comment by kmaincent** [comment]
Config added it was indeed an issue.
