### ISSUE TITLE
Linux kernel compilation fails with scripts/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory

### ISSUE THREAD

**Issue by FrankBau** [bootlin/buildroot-external-st#23]
Can be easily fixed by adding `libssl-dev` to the pre-requisites in https://github.com/bootlin/buildroot-external-st#pre-requisites.
Found on a Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 server as build host.
hth
KnarfB

**Comment by tpetazzoni** [comment]
Not the right fix. Buildroot can build host-openssl as a dependency of Linux by enabling BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL=y.

**Comment by kmaincent** [comment]
Issue already reported here: #17 
Are you using the same kernel Configuration as the one in the BR2_EXTERNAL?

**Comment by FrankBau** [comment]
Yes, I did a clean build in a new folder:
```
git clone -b st/2021.02 https://github.com/bootlin/buildroot.git
git clone -b st/2021.02 https://github.com/bootlin/buildroot-external-st.git
cd buildroot
make BR2_EXTERNAL=../buildroot-external-st st_stm32mp157c_dk2_defconfig
make
```
on that Debian server I use as workaround for #22.

**Comment by FrankBau** [comment]
@tpetazzoni : then I see two issues here:
- build tainted by host openssl, because the fix worked
- BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL missing in the defconfigs (or in the Kernel config?)

**Comment by tpetazzoni** [comment]
_build tainted by host openssl_ => this is inherent to cross-compilation in general, it's impossible to fully isolate from what's on the host machine
_BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL missing in the defconfigs_ => yes, I agree

**Comment by kmaincent** [comment]
It is indeed an issue, I just add the config to fix it, thanks.
