### ISSUE TITLE
Ecosystem 4.0.0 update

### ISSUE THREAD

**Issue by x3ccd4828** [bootlin/buildroot-external-st#25]
Hi, 

Are you planning to update the optee demo example to work with the newly released ecosystem 4.0.0?

**Comment by tpetazzoni** [comment]
Yes, we are about to release a complete update of the entire buildroot-external-st for the recently released 4.0.0 ecosystem from ST.

**Comment by x3ccd4828** [comment]
Thanks for the reply, I will keep an eye out.
