### ISSUE TITLE
Build failed "The headers or library files could not be found for jpeg installing Pillow"

### ISSUE THREAD

**Issue by markgajevskis** [bootlin/buildroot-external-st#26]
After following the manual and running:
`make BR2_EXTERNAL=../buildroot-external-st st_stm32mp157f_dk2_demo_defconfig`
on Ubuntu 20.04.1 I get following error:
`The headers or library files could not be found for jpeg installing Pillow`

It looks like 
`sudo apt install libjpeg-dev zlib1g-dev`
can fix this issue

So maybe consider to add this to the mandatory packages in README

**Comment by tpetazzoni** [comment]
Thanks for the bug report! I have addressed this in the latest st/2022.02 branch of https://github.com/bootlin/buildroot by making a change in the python-pillow package. It no longer needs the jpeg library on the host machine.
