### ISSUE TITLE
Custom DTS when building OPTEE-OS example

### ISSUE THREAD

**Issue by x3ccd4828** [bootlin/buildroot-external-st#27]
Would you be able to add an example that uses a custom DTS file for building OPTEE-OS?

Currently, OPTEE-OS doesn't support custom dts path nor do I see a way to load custom device trees.

**Comment by tpetazzoni** [comment]
That's a very good point indeed. We'll add that to our TODO-list. We mainly need to figure out how to convince the OPTEE-OS build system to use an externally provided Device Tree file. Once that's figured out, integrating that in the Buildroot build process should not be too difficult.

**Comment by x3ccd4828** [comment]
I tried looking at the Makefile.sdk from STM found in they yocto dev package (stm32mp1-openstlinux-5.15-yocto-kirkstone-mp1-v22.06.15/sources/arm-ostl-linux-gnueabi/optee-os-stm32mp-3.16.0-stm32mp1-r1-r0).
But it wasn't that straightforward. I will keep digging in parallel.

**Comment by DerArtem** [comment]
Any news on this? Another option would be to specify an a path on the filesystem with custom op-tee sources. But this also does not work right now.

**Comment by kmaincent** [comment]
Hello, this feature will be added in the next 2022.02.7 release.
FYI: The solution is to use the CFG_EMBED_DTB_SOURCE_FILE configure option.
