### ISSUE TITLE
How to add gdbserver to target?

### ISSUE THREAD

**Issue by alextsai-tainan** [bootlin/buildroot-external-st#32]
How to add gdbserver to target?
I have added option "BR2_TOOLCHAIN_EXTERNAL_GDB_SERVER_COPY"  in menuconfig.
But gdbserver is still not on the target.

**Comment by kmaincent** [comment]
~~The option to add gdb server on the target is BR2_PACKAGE_GDB_SERVER.~~
Sorry I replied too quickly, indeed if there is a GDB built for the target architecture in the toolchain this option should work. As it is done at early build you need to do a build from scratch or you could also use the `${toolchain-name}-reinstall` command. For bootlin toolchain example, the command is `make toolchain-external-bootlin-reinstall`

**Comment by tpetazzoni** [comment]
Solution was provided by @kmaincent
