### ISSUE TITLE
How can I build bps for a board with emmc boot？

### ISSUE THREAD

**Issue by jacky123pqh** [bootlin/buildroot-external-st#39]
Hi,
  bootlin,would u give a exampe for how to build bps for a emmc boot board?Thanks.I read TF-A code,and get the macro STM32MP_EMMC is for emmc boot device;then following "[Using Device Tree files generated by STM32 CubeMX] "and modify BR2_TARGET_ARM_TRUSTED_FIRMWARE_ADDITIONAL_VARIABLES="STM32MP_EMMC=1 "instead "STM32MP_SDMMC=1",but TF-A build failed, with message:
drivers/st/ddr/stm32mp1_ram.c:  in function‘stm32mp1_ddr_clk_enable’:
drivers/st/ddr/stm32mp1_ram.c:34:28:error： ‘DDRPHYC’ undeclared (first use in this function); did you mean ‘DDRPHYC_PIR’?
ddrphy_clk = clk_get_rate(DDRPHYC);

**Comment by tpetazzoni** [comment]
Sorry, but what is "bps" in this context? What are you trying to do?

**Comment by tpetazzoni** [comment]
Not enough details provided, no feedback from submitter, closing.
