### ISSUE TITLE
Linux Frame Buffer (fb0) missing

### ISSUE THREAD

**Issue by MfaizR** [bootlin/buildroot-external-st#46]
Hi, 
Can i enable the linux frame buffer (fb) together with the OpenGL? Setting already done but I cant see the device in /dev. please advise.
Thanks

**Comment by tpetazzoni** [comment]
Could you clarify what your final goal is? What graphics library do you want to use?

**Comment by MfaizR** [comment]
Hi Thomas,
I am trying to put psplash output to the fb0, since that is the psplash default output correct? I understand that it can be redirected to GPU but could not make it work. any advise?

**Comment by mstaack** [comment]
for reference: https://github.com/g0hl1n/psplash

buildroot has a build-in boot-image feature afaik. (have seen a menu entry for that)

**Comment by MfaizR** [comment]
> for reference: https://github.com/g0hl1n/psplash
> 
> buildroot has a build-in boot-image feature afaik. (have seen a menu entry for that)

Hi @mstaack , 
I never see any of that besides psplash, care to clarify further?
i am looking for the psplash-drm source code, which I believe is for the OpenGL usage.
Thanks

**Comment by MfaizR** [comment]
> Hi, Can i enable the linux frame buffer (fb) together with the OpenGL? Setting already done but I cant see the device in /dev. please advise. Thanks

@tpetazzoni @mstaack this has been resolved. I refer to this https://github.com/bootlin/buildroot-external-st/issues/31#issue-1511501266
