### ISSUE TITLE
How to perform secure boot from buildroot proejct ??

### ISSUE THREAD

**Issue by edin-lee77** [bootlin/buildroot-external-st#55]
We are evaluating secure boot mode with stm32mp135f MPU
Is there any documents to enable secure boot on stm32mp135f evk board?

**Comment by kmaincent** [comment]
Hello, please look at the ST wiki:
https://wiki.st.com/stm32mpu/wiki/STM32_MPU_ROM_code_secure_boot
There is also a how-to but with Yocto distribution:
https://wiki.st.com/stm32mpu/wiki/How_to_perform_Secure_Boot_from_Distribution_package
