### ISSUE TITLE
use m5stack_coremp135_defconfig, serial port doesn't work.

### ISSUE THREAD

**Issue by RichSj** [bootlin/buildroot-external-st#58]
I did use m5stack_coremp135_515_defconfig build image, window 10 device manager find COM1(system default) and COM 5 work fine, but use m5stack_coremp135_defconfig, window 10 device manager only find COM 1 for system itself.
I build at 2024 Sep 21.  use Ver 2024.02.3 from bootlin / buildroot-extrnal-st

**Comment by kmaincent** [comment]
We don't have the defconfigs you are talking about. We can't help you without more information on the issue.

**Comment by RichSj** [comment]
These for CoreMP135 product, I got feedback, they request only use one config, if use second config, have to use one parameter clear early build.
